lec3/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name ='index'),
    path('<str:name>',views.greet, name='greet'),
]

lec3/lec3/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/',include('hello.urls')),
    path('newyear/', include('newyear.urls')),
    path('task/', include('task.urls'))
]

lec3/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name='index')
]

lec3/task/urls.py
from django.urls import  path
from . import views

app_name = 'task'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('add', views.add, name ='add'),
]

lec3/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'hello/index.html')

def greet(request, name):
    return render(request,  'hello/greet.html',
        {"name": name.capitalize()})

lec3/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.

def index(request):
    now = datetime.datetime.now()
    return render(request, 'newyear/index.html',{
        "now" : now.month == 1 and now.day == 1
    })

lec3/task/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django import forms
from django.urls import reverse

class NewTaskForm(forms.Form):
    task = forms.CharField()


# Create your views here.
def index(request):
    if 'tasks' not in request.session:
        request.session['tasks'] = []
    return render(request, 'task/index.html',{
        'tasks': request.session['tasks']
    })

def add(request):
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data['task']
            request.session['tasks'] += [task]
            
            return HttpResponseRedirect(reverse('task:index'))
        else:
            return render(request, 'task/add.html',{
                'form': form
            })
    return render(request, 'task/add.html',{
        'form': NewTaskForm()
    })

lec3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello {{name}}</h1>
</body>
</html>

lec3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello World</h1>
</body>
</html>

lec3/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=P, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'newyear/style.css'%}">
</head>
<body>
    {% if newyear %}
    <h1>Yes</h1>
    {% else %}
    <h1>No</h1>
    {% endif %}
</body>
</html>

lec3/task/templates/task/add.html
{% extends 'task/index.html' %}

{% block body %}
    <h1>Add Tasks</h1>
    <form action="{% url 'task:add' %}" method="Post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'task:index' %}">Goto Task</a>
{% endblock %}

lec3/task/templates/task/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Tasks</h1>
    {% block body%}
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
            <li>No Task added</li>
        {% endfor %}
        <a href="{% url 'task:add' %}">Add a Task</a>
    {% endblock%}
    
</body>
</html>